version: '3'
services:
  db:
    image: postgres:latest
    container_name: web-service-gin-postgres1
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    container_name: admin-db
    restart: always
    ports:
      - "8080:8080"